creator :
	cd creator && make

editor :
	cd editor && make

all :
	cd editor && make
	cd creator && make

clean :
	cd editor && make clean
	cd creator && make clean

install :
	cd editor && make install
	cd creator && make install

uninstall :
	cd editor && make uninstall
	cd creator && make uninstall

reinstall :
	cd editor && make reinstall
	cd creator && make reinstall


